volumes:
  mysql:

services:
  mysql:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    user: "1000:1000" # UID:GID yang sama
    ports:
      - 8081:80
    links:
      - mysql
    volumes:
      - ./nextcloud:/var/www/html
      - ./data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.local`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      # - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    restart: always
    # user: "1000:1000" # UID:GID yang sama
    ports:
      - "8082:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent_config:/config
      - ./data/admin/files/Movie:/downloads
    depends_on:
      - nextcloud

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    user: "1000:1000" # UID:GID yang sama
    network_mode: "host"
    ports:
      - "8096:8096"
      - "8920:8920"  # SSL jika diaktifkan
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - ./data:/media:cached
    environment:
      - JELLYFIN_PublishedServerUrl=192.168.1.100 # IP lokal host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      # - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Untuk membaca label Docker
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/acme.json  # Opsional, untuk sertifikat SSL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"  # Dashboard domain
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"